sonar.organization=aleksey19988
sonar.projectKey=aleksey19988_go-project-244
sonar.projectName=go-project-244

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/testdata/**,**/mocks/**,**/bin/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go

# Coverage
sonar.go.coverage.reportPaths=coverage.out

# Исключаем из покрытия
sonar.coverage.exclusions=**/cmd/**