sonar.organization=aleksey19988
sonar.projectKey=aleksey19988_go-project-244
sonar.projectName=go-project-244

# Go settings
sonar.language=go
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/testdata/**,**/mocks/**,**/bin/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.test.exclusions=**/vendor/**

# Coverage
sonar.go.coverage.reportPaths=coverage.out

# Опционально — что исключать из покрытия
sonar.coverage.exclusions=**/cmd/**,**/migrations/**,**/config/**,**/dto/**,**/entity/**